---
title: "diplomatic-gifts-extra-code"
author: "Alex Cookson"
date: "10/05/2020"
output: html_document
---
### Unused code

```{r recipients, eval = FALSE}
gift_words_by_person <- gifts %>%
  # Select unique gift descriptions to pare down travel "gifts" that often take up multiple lines
  distinct(gift_description, .keep_all = TRUE) %>%
  # Filter out travel
  filter(!str_detect(str_to_lower(gift_description), "travel")) %>%
  transmute(id,
            recipient,
            gift_description = str_to_lower(gift_description)) %>%
  unnest_tokens(word, gift_description) %>%
  anti_join(stop_words, by = "word") %>%
  anti_join(custom_stop_words, by = "word") %>%
  filter(str_detect(word, "[a-z]"),
         !is.na(recipient))

gift_words_by_person %>%
  distinct(id, recipient, word) %>%
  count(word, recipient) %>%
  bind_tf_idf(word, recipient, n) %>%
  filter(n >= 3) %>%
  arrange(desc(tf_idf)) %>%
  filter(str_detect(recipient, c("President")),
         !str_detect(recipient, "Vice"),
         !str_detect(recipient, "Assistant")) %>%
  group_by(recipient) %>%
  top_n(6) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, by = tf_idf, within = recipient, sep = ": ")) %>%
  ggplot(aes(tf_idf, word, fill = recipient)) +
  geom_col() +
  scale_y_reordered(sep = ": ") +
  scale_fill_fish(option = "Epibulus_insidiator",
                  discrete = TRUE) +
  facet_wrap(~ recipient, scales = "free_y") +
  labs(title = "What words are associated with different countries' diplomatic gifts to the U.S.?") +
  theme(legend.position = "none",
        axis.text.y = element_text(size = 14),
        strip.background = element_blank(),
        strip.text = element_text(colour = "black", face = "bold"))
```

```{r president-gift-words, eval = FALSE}
gift_words_by_person %>%
  filter(str_detect(recipient, "^President") | str_detect(recipient, "President of the United States")) %>%
  count(word, sort = TRUE) %>%
  top_n(20, wt = n) %>%
  mutate(word = fct_reorder(word, n)) %>%
  ggplot(aes(n, word, fill = word)) +
  geom_col() +
  scale_fill_fish(option = "Epibulus_insidiator",
                  discrete = TRUE,
                  direction = -1) +
  theme(legend.position = "none")
```

```{r gift-value-by-country, eval = FALSE}
top_20_countries <- gifts %>%
  group_by(donor_country) %>%
  summarise(value_usd = sum(value_usd, na.rm = TRUE)) %>%
  filter(!is.na(donor_country)) %>%
  top_n(20, wt = value_usd) %>%
  pull(donor_country)

gifts %>%
  group_by(donor_country) %>%
  summarise(value_usd = sum(value_usd, na.rm = TRUE)) %>%
  filter(!is.na(donor_country)) %>%
  top_n(20, wt = value_usd) %>%
  mutate(donor_country = fct_reorder(donor_country, value_usd)) %>%
  ggplot(aes(value_usd, donor_country, fill = donor_country)) +
  geom_col() +
  scale_x_continuous(labels = label_dollar()) +
  scale_fill_fish(option = "Epibulus_insidiator",
                  discrete = TRUE) +
  theme(legend.position = "none")

gifts %>%
  filter(donor_country %in% top_20_countries,
         !is.na(value_usd)) %>%
  mutate(donor_country = fct_reorder(donor_country, value_usd, median)) %>%
  ggplot(aes(value_usd, donor_country, fill = donor_country)) +
  geom_boxplot() +
  scale_x_log10(labels = label_dollar()) +
  scale_fill_fish(option = "Epibulus_insidiator",
                  discrete = TRUE) +
  theme(legend.position = "none")
```

```{r top-country-words, eval = FALSE}
gift_words %>%
  distinct(id, donor_country, word) %>%
  count(word, donor_country) %>%
  bind_tf_idf(word, donor_country, n) %>%
  filter(n >= 3) %>%
  arrange(desc(tf_idf)) %>%
  group_by(donor_country) %>%
  top_n(1) %>%
  ungroup() %>%
  View()
```
