---
title: "Empirical Bayes Estimation"
author: "Alex Cookson"
date: "31/05/2020"
output: html_document
---

Introduction. Children's books ratings with breakdown of 1-5 stars:

1. Star rating inference with shrinkage
2. Re-scaling to make use of full 1-5 star range


## Setup

```{r setup-and-import, warnings = FALSE, message = FALSE}
library(tidyverse)
library(scales)
library(stats4)
library(broom)
library(extrafont)
library(fishualize)
library(gganimate)

theme_set(theme_light())

books <- read_tsv("https://raw.githubusercontent.com/tacookson/data/master/childrens-book-ratings/childrens-books.txt") %>%
  # Select only fields we're using (book identifiers and ratings)
  select(isbn, title, rating:rating_1) %>%
  # Get rid of duplicates
  distinct(isbn, title, .keep_all = TRUE)
```


## Data inspection

Distribution of ratings:

- Centred on 3.whatever
- Two spikes 

```{r original-rating-distribution, fig.align = 'center', fig.width = 8, fig.asp = 0.618}
books %>%
  filter(!is.na(rating)) %>%
  ggplot(aes(rating)) +
  geom_histogram(binwidth = 0.1)
```


```{r rating-pct-distribution, fig.align = 'center', fig.width = 8, fig.asp = 0.618}
rating_pct <- books %>%
  filter(rating_count > 0) %>%
  mutate_at(vars(rating_5:rating_1), ~ . / rating_count)

# Filter for books with at least 500 reviews
rating_pct %>%
  filter(rating_count > 500) %>%
  pivot_longer(cols = rating_5:rating_1) %>%
  ggplot(aes(value)) +
  geom_histogram(binwidth = 0.02) +
  facet_wrap(~ name)
```

```{r dirichlet-multinomial, message = FALSE}
# Create a matrix to feed our MLE of Dirichlet-Multinomial
rating_matrix <- books %>%
  filter(rating_count > 1000) %>%
  select(rating_5:rating_1) %>%
  as.matrix()

# Fit a Dirichlet Multinomial distribution
dm_fit <- DirichletMultinomial::dmn(rating_matrix, 1)

# Write a function to tidy DMN object (which dm_fit is)
tidy.DMN <- function(x, ...) {
  ret <- as.data.frame(x@fit)
  as_tibble(fix_data_frame(ret, c("conf.low", "estimate", "conf.high")))
}

# Tidy the DMN fit
dm_params <- tidy(dm_fit)

# Get parameters into a useful format
par <- dm_params %>%
  separate(term, into = c("constant", "rating_stars"), sep = "_", convert = TRUE) %>%
  select(rating_stars,
         prior_ratings = estimate)

# Calculate total prior ratings and mean (used for graphing)
par_total <- sum(par$prior_ratings)
par_mean <- par %>%
  summarise(prior_rating = sum(rating_stars * prior_ratings) / sum(prior_ratings)) %>%
  pull(prior_rating)
```

```{r calculate-empirical-bayes-rating, message = FALSE}
# Calculate empirical Bayes rating using our prior
books_eb <- books %>%
  pivot_longer(rating_5:rating_1,
               names_to = c("rating_stars"),
               names_pattern = "rating_(.*)",
               names_transform = list(rating_stars = as.integer),
               values_to = "ratings") %>%
  left_join(par, by = "rating_stars") %>%
  group_by(isbn, title, rating_count) %>%
  summarise(rating_calc = sum(rating_stars * ratings) / sum(ratings),
            rating_eb = sum(rating_stars * (ratings + prior_ratings)) / sum(ratings + prior_ratings)) %>%
  ungroup()
```



### Animations

```{r books-shrunk-data}
books_shrunk <- books_eb %>%
  filter(rating_count > 0) %>%
  select(isbn, title, rating_count, rating_calc, rating_eb) %>%
  pivot_longer(rating_calc:rating_eb, names_to = "rating_type", values_to = "rating") %>%
  mutate(rating_type = ifelse(rating_type == "rating_calc", "Original Rating", "Empirical Bayes Rating"))
```

```{r animation-all-ratings, fig.align = 'center', fig.width = 8, fig.asp = 0.7}
# Create base plot
p <- books_shrunk %>%
  ggplot(aes(rating_count, rating, col = rating_count)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = par_mean,
             lty = 2,
             size = 1,
             col = "red") +
  scale_colour_fish(option = "Ostracion_whitleyi", trans = "log") +
  scale_x_log10(labels = label_comma(accuracy = 1),
                breaks = 10 ^ c(0:5)) +
  labs(subtitle = "Dashed line shows Bayesian prior for a book with 0 ratings",
       x = "Number of ratings",
       y = "Rating") +
  theme(legend.position = "none",
        text = element_text(family = "Bahnschrift"),
        axis.text = element_text(size = 12),
        plot.title = element_text(size = 18),
        panel.grid.minor.x = element_blank())

# Set animation parameters
anim <- p +
  transition_states(rating_type,
                    transition_length = 1.5,
                    state_length = 3.5) +
  ease_aes("cubic-in-out") +
  ggtitle("{closest_state}")

# Create animation
anim
```

```{r animation-500-ratings-or-less, fig.align = 'center', fig.width = 8, fig.asp = 0.7}
# Create base plot
p_filtered <- books_shrunk %>%
  filter(rating_count <= 500) %>%
  ggplot(aes(rating_count, rating, col = rating_count)) +
  geom_point(alpha = 0.4) +
  geom_hline(yintercept = par_mean,
             lty = 2,
             size = 1,
             col = "red") +
  scale_colour_fish(option = "Ostracion_whitleyi") +
  labs(subtitle = "Dashed line shows Bayesian prior for a book with 0 ratings",
       x = "Number of ratings",
       y = "Rating") +
  theme(legend.position = "none",
        text = element_text(family = "Bahnschrift"),
        axis.text = element_text(size = 12),
        plot.title = element_text(size = 18))

# Set animation parameters
anim_filtered <- p_filtered +
  transition_states(rating_type,
                    transition_length = 1.5,
                    state_length = 3.5) +
  ease_aes("cubic-in-out") +
  ggtitle("{closest_state}")

# Create animation
anim_filtered
```

```{r shrinkage-amount, fig.align = 'center', fig.width = 8, fig.asp = 0.618}
# Amount that the score was changed based on shrinkage
books_eb %>%
  select(isbn, title, rating_count, rating_calc, rating_eb) %>%
  filter(rating_count <= 500) %>%
  mutate(rating_change = rating_eb - rating_calc) %>%
  ggplot(aes(rating_count, rating_change, col = rating_count)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, lty = 2, size = 1, col = "red") +
  scale_colour_fish(option = "Ostracion_whitleyi") +
  expand_limits(y = c(-1, 2)) +
  scale_y_continuous(breaks = seq(-1, 2, by = 0.5)) +
  labs(title = "Fewer Ratings = More Shrinkage",
       subtitle = "As books get more ratings, our Bayesian prior has less influence",
       x = "Number of ratings",
       y = "Change in rating from shrinkage") +
  theme(legend.position = "none",
        text = element_text(family = "Bahnschrift"),
        axis.text = element_text(size = 12),
        plot.title = element_text(size = 18),
        panel.grid.minor.y = element_blank())
```




## Scaling

```{r scale}
scaled <- books_eb %>%
  mutate(scaled_rating = rescale(rating_eb, to = c(1, 5)))

scaled %>%
  ggplot(aes(scaled_rating)) +
  geom_histogram(binwidth = 0.1)
```