---
title: "fictional-character-personalities"
author: "Alex Cookson"
date: "31/07/2020"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
library(tidyverse)
library(tidymodels)
library(tidytext)

theme_set(theme_light())

personalities <- read_tsv("~/data/fictional-character-personalities/personalities.txt")
```

```{r pride-and-prejudice-example}
personalities %>%
  filter(!is_emoji,
         fictional_work == "Pride and Prejudice",
         character_name %in% c("Elizabeth Bennet", "Jane Bennet", "Lydia Bennet",
                               "Mr. Darcy", "Mr. William Collins", "George Wickham")) %>%
  mutate(mean = mean - 50) %>%
  group_by(character_name) %>%
  top_n(8, abs(mean)) %>%
  ungroup() %>%
  mutate(spectrum_label = ifelse(mean > 0, spectrum_high, spectrum_low),
         mean = abs(mean),
         spectrum_label = reorder_within(spectrum_label, mean, character_name)) %>%
  ggplot() +
  geom_col(aes(mean, spectrum_label, fill = character_name), show.legend = FALSE) +
  scale_y_reordered() +
  facet_wrap(~ character_name, scales = "free_y") +
  labs(title = "",
       x = "Score (out of 50)",
       y = "Personality Trait")
```

```{r star-trek-tng-example}
personalities %>%
  filter(!is_emoji,
         fictional_work == "Star Trek: The Next Generation",
         character_name %in% c("Jean-Luc Picard", "William Riker", "Geordi La Forge",
                               "Worf", "Beverly Crusher", "Data")) %>%
  mutate(mean = mean - 50) %>%
  group_by(character_name) %>%
  top_n(8, abs(mean)) %>%
  ungroup() %>%
  mutate(spectrum_label = ifelse(mean > 0, spectrum_high, spectrum_low),
         mean = abs(mean),
         spectrum_label = reorder_within(spectrum_label, mean, character_name)) %>%
  ggplot() +
  geom_col(aes(mean, spectrum_label, fill = character_name), show.legend = FALSE) +
  scale_y_reordered() +
  facet_wrap(~ character_name, scales = "free_y") +
  labs(title = "",
       x = "Score (out of 50)",
       y = "Personality Trait")
```



```{r wide-personalities}
personalities %>%
  mutate(spectrum_name = paste(spectrum_low, spectrum_high, sep = "_")) %>%
  select(character_code, spectrum_name, mean) %>%
  pivot_wider(names_from = spectrum_name, values_from = mean, values_fill = NA)
```

```{r helper-datasets}
character_list <- personalities %>%
  distinct(character_code, fictional_work, character_name)

spectrum_list <- personalities %>%
  distinct(spectrum, spectrum_low, spectrum_high)

interesting_works <- c("Arrested Development", "Anna Karenina", "Brooklyn Nine-Nine", "Star Trek: Deep Space Nine", "Friends",
                       "Game of Thrones", "The Good Place", "Harry Potter", "The Lion King", "Mad Men", "Parks and Recreation",
                       "Seinfeld", "Silicon Valley", "Star Wars", "Star Trek: The Next Generation", "Pride and Prejudice")
```



### Worf's character evolution

Is Worf rated differently between TNG and DS9?

```{r worf-difference}
personalities %>%
  filter(character_name == "Worf",
         !is_emoji) %>%
  select(-character_code, -ratings, -sd, -is_emoji) %>%
  pivot_wider(names_from = fictional_work, values_from = mean) %>%
  rename(ds9 = `Star Trek: Deep Space Nine`,
         tng = `Star Trek: The Next Generation`) %>%
  mutate(change = ds9 - tng) %>%
  top_n(20, abs(change)) %>%
  arrange(desc(change))
```



### Use `tidymodels` to implement Principal Component Analysis (PCA)

Resources for PCA:

- `tidymodels` documentation: https://recipes.tidymodels.org/reference/step_pca.html
- Julia Silge's walkthrough: https://juliasilge.com/blog/best-hip-hop/

```{r data-for-pca}
pca_data <- personalities %>%
  filter(!is_emoji) %>%
  select(character_code, spectrum, mean) %>%
  pivot_wider(names_from = spectrum, values_from = mean)
```

```{r initial-pca}
# Write recipe for PCA
pca_recipe <- recipe(~ ., data = pca_data) %>%
  update_role(character_code, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

# Inspect a few principal components to see what they capture
prep(pca_recipe) %>%
  tidy(type = "coef", number = 2) %>%
  left_join(spectrum_list, by = c("terms" = "spectrum")) %>%
  mutate(label = ifelse(value > 0, spectrum_high, spectrum_low),
         abs_value = abs(value)) %>%
  filter(component %in% paste0("PC", 1:6)) %>%
  group_by(component) %>%
  top_n(12, abs_value) %>%
  ungroup() %>%
  mutate(label = reorder_within(label, by = abs_value, within = component, sep = "_")) %>%
  ggplot(aes(abs_value, label)) +
  geom_col() +
  facet_wrap(~ component, scales = "free_y", ncol = 2)

# Inspect PCA to see which principal components account for what % of variance
prep(pca_recipe) %>%
  tidy(type = "variance", number = 2) %>%
  filter(terms == "cumulative percent variance") %>%
  mutate(pct_variance = value / 100) %>%
  ggplot(aes(component, pct_variance)) +
  geom_line() +
  scale_y_continuous(labels = label_percent())
```

```{r second-pca}
# Add threshold to PCA to cover 90% of variance
pca_recipe <- recipe(~ ., data = pca_data) %>%
  update_role(character_code, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors(),
           threshold = 0.9)

# Run PCA
personality_pca <- prep(pca_recipe) %>%
  juice()
```

```{r}
character_list %>%
  left_join(personality_pca, by = "character_code") %>%
  filter(fictional_work %in% interesting_works) %>%
  ggplot(aes(PC01, PC06)) +
  geom_text(aes(label = character_name), check_overlap = TRUE)
```


### STILL NEEDS WORK

Clustering rough code

```{r clustering}
clustering_data <- personality_pca %>%
  select(-character_code)

tibble(k = 1:20) %>%
  mutate(model = map(k, ~ kmeans(clustering_data, .x)),
         glanced_model = map(model, glance)) %>%
  unnest(cols = c(glanced_model)) %>%
  ggplot(aes(k, tot.withinss)) +
  geom_point() +
  geom_line()

cluster_model <- kmeans(clustering_data, centers = 12) %>%
  augment(clustering_data) %>%
  bind_cols(character_list) %>%
  rename(cluster = .cluster) %>%
  select(character_code, fictional_work, character_name, cluster, everything()) %>%
  filter(fictional_work %in% interesting_works)

cluster_model %>%
  select(cluster, PC01:PC26) %>%
  group_by(cluster) %>%
  summarise_all(mean) %>%
  pivot_longer(PC01:PC26) %>%
  #mutate(cluster = reorder_within(cluster, by = value, within = name, sep = "_")) %>%
  ggplot(aes(value, cluster)) +
  geom_col() +
  facet_wrap(~ name, scales = "free_x")


cluster_model %>%
  ggplot(aes(PC01, PC02, colour = cluster)) +
  geom_text(aes(label = paste0(character_name, "\n(", fictional_work, ")")), check_overlap = TRUE, size = 3)
```



### APPENDIX

```{r sample-random-character}
personalities %>%
  filter(character_name %in% sample(unique(character_name), 1),
         !is_emoji) %>%
  top_n(12, abs(mean - 50)) %>%
  arrange(desc(mean))
```







